# Generated by Django 4.0 on 2022-01-02 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=160)),
                ('card_number', models.CharField(max_length=20)),
                ('security_code', models.CharField(max_length=5)),
                ('expiration', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
                ('date_edit', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to='mypass.user')),
            ],
        ),
    ]
