# Generated by Django 4.0 on 2022-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
