# Generated by Django 4.0 on 2022-01-02 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0003_card_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=160)),
                ('account_type', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('pin_number', models.CharField(max_length=10)),
                ('branch_address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
                ('date_edit', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bankaccount', to='mypass.user')),
            ],
        ),
    ]
