# Generated by Django 4.0 on 2022-01-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0004_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
