# Generated by Django 4.0 on 2022-01-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0005_password_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='share_url',
            field=models.URLField(default=None),
        ),
    ]
