# Generated by Django 4.0 on 2022-01-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0006_note_share_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='share_url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
