# Generated by Django 4.0 on 2022-01-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0007_alter_note_share_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('system', models.CharField(blank=True, max_length=500)),
                ('system_version', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('date_login', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_history', to='mypass.user')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
