# Generated by Django 4.0 on 2022-01-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0008_loginhistory_alter_address_email_alter_address_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
