# Generated by Django 4.0 on 2022-01-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0009_rename_ip_address_loginhistory_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='system_version',
        ),
    ]
