# Generated by Django 4.0 on 2022-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0012_delete_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='share_url',
            field=models.CharField(default=False, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='share_url',
            field=models.CharField(default=False, editable=False, max_length=100),
        ),
    ]
