# Generated by Django 4.0 on 2022-01-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0013_address_share_url_alter_note_share_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='share_url',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='share_url',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
    ]
