# Generated by Django 4.0 on 2022-01-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0014_alter_address_share_url_alter_note_share_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='domain_password',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='PasswordEncrypt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_key', models.CharField(max_length=500)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypt_password', to='mypass.password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_encrypt_pass', to='mypass.user')),
            ],
        ),
    ]
