# Generated by Django 4.0 on 2022-01-04 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0015_alter_password_domain_password_passwordencrypt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_encrypt_pass', to='mypass.user')),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordEncrypt',
        ),
    ]
