# Generated by Django 4.0 on 2022-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0017_encryptpassword_delete_encryptcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptpassword',
            name='key',
            field=models.BinaryField(max_length=500),
        ),
        migrations.AlterField(
            model_name='password',
            name='domain_password',
            field=models.BinaryField(max_length=500),
        ),
    ]
