# Generated by Django 4.0 on 2022-01-04 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0018_alter_encryptpassword_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(max_length=500)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypt_card', to='mypass.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_encrypt_card', to='mypass.user')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(max_length=500)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypt_bankaccount', to='mypass.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_encrypt_bankaccount', to='mypass.user')),
            ],
        ),
    ]
