# Generated by Django 4.0 on 2022-01-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypass', '0020_alter_card_card_number_alter_card_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number_ending',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
